<a href="https://colab.research.google.com/github/jhaanshu17/SQL/blob/main/6_Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Array Dimensions

1D Array

2D Array

3D Array

In [3]:
import numpy as np     # importing numpy library

In [4]:
A = np.array(5)        # Scalar Array
A

array(5)

In [5]:
np.ndim(A)               # Dimension method

0

In [11]:
One = np.array([1, 2, 3, 4, 5])
# Two = np.array([[1, 2, 3], [4, 5, 6]])
Three = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

In [12]:
Three

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
One

array([1, 2, 3, 4, 5])

In [13]:
Three.shape
np.ndim(Three)

3

In [ ]:
np.ndim(One)
np.ndim(Two)
np.ndim(Three)

3

# List vs Numpy Array

In [14]:
list1 = [1,4.0,'apple']                     # List - Different Datatypes
arr = np.array([1, 2, 3, 4, 5])             # Array - Similar Datatypes

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
arr = np.array([1, 2, 3.9, 'apple'])        # Type Conversion

In [17]:
arr

array(['1', '2', '3.9', 'apple'], dtype='<U32')

In [18]:
arr = np.array([1, 2, 3, 4, 5])             # Allows Mathematical Operations

# arr/5
list1/5

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [19]:
arr/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

# More Advantages of Numpy Array over list

*   Array consumes less memory
*   Array are faster than lists



In [20]:
arr+5

array([ 6,  7,  8,  9, 10])

# Reshaping arrays

Reshaping means changing the shape of an array.

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])   # 1D Array

# 1D to 2D Array
newarr = arr.reshape(3, 4)


In [22]:
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [31]:
# 1D to 3D Array

newarr = arr.reshape(2, 2, 3)    # x,y,z: x = matrix, y = rows, z = cols


In [32]:
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# print(newarr)

# Array Indexing

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

In [33]:
arr = np.array([1, 2, 3, 4])              # Accessing 1D Array

print(arr[3])

4


In [34]:
print(arr[0] + arr[1])                 # Addition of 2 elements

3


In [39]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])  # Accessing 2D Array
arr.shape

print(arr[1, 0])                          # 1st row 4th element
print(arr[1, 1])                          # 2nd row 5th element
print(arr[1,3])

6
7
9


In [40]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])   # Accessing 3D Array

arr3.shape
# print(arr3)
# print(arr3[0, 0, 2])               # 1st matrix, 1st row, 3rd column
# # print(arr3[1, 1, 1])               # 1st matrix, 2nd row, 1st column
# print(arr3[0,1,0])

(2, 2, 3)

In [45]:
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [48]:
print(0,1,2)

0 1 2


In [55]:
print(arr3[1,1,2])

12
